codecov:
  branch: master
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...3100"

  status:
    project:
      default:
        target: auto
        branches: null

    patch:
      default:
        enabled: false

    changes:
      default:
        branches: null

  ignore:
    - test/*
